
package library;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class StaffForm extends javax.swing.JFrame {
  
   private javax.swing.JTable jTableBorrowed;
   private JLabel pasteLabel;
    private Dashboard dashboard;
    private ArrayList<Book> books;
    private ArrayList<BorrowedBook> theLastOne;
   
    
    public StaffForm(ArrayList<Book> books, Dashboard dashboard, ArrayList<BorrowedBook> theLastOne) {
        initComponents();
        this.books = books;
        this.theLastOne = theLastOne;
        this.dashboard = dashboard;
        pasteLabel = new JLabel("Paste initialization code here:");
        add(pasteLabel, BorderLayout.NORTH);
        populateTable1();
        populateTable2();
        dashboard.TheLastOne();
    }
    
  private void initDashboard() {
        dashboard = new Dashboard(this);
    }

    public StaffForm() {
    initComponents();
    dashboard = new Dashboard(this);
    

   
}

public StaffForm(ArrayList<Book> books, Dashboard dashboard) {
    this(books, dashboard, new ArrayList<BorrowedBook>());
}


public void populateTable1() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    for (BorrowedBook borrowedBook : theLastOne) {
        model.addRow(new Object[]{
            borrowedBook.getTitle(),
            borrowedBook.getAuthor(),
            borrowedBook.getBorrowerName(),
            borrowedBook.getBorrowDate(),
            borrowedBook.getReturnDate()
        });
    }
}

public void populateTable2() {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); 

    for (Book book : books) {
        model.addRow(new Object[]{
            book.getTittle(),
            book.getAuthor(),
            book.getCategory()
        });
    }
}


private void updateJTable1WithBorrowedBooks() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear existing rows

    // Assuming theLastOne is the list of borrowed books
    for (BorrowedBook borrowedBook : theLastOne) {
        model.addRow(new Object[]{borrowedBook.getTitle(), borrowedBook.getAuthor(), borrowedBook.getBorrowerName(), borrowedBook.getBorrowDate(), borrowedBook.getReturnDate()});
    }

    // Notify the table of the changes
    model.fireTableDataChanged();
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbLogout = new javax.swing.JButton();
        jpSearch2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtSearchTittle2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtSearchAuthor2 = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtSearchAuthor3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jpSearch3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jtSearchTittle3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtSearchAuthor4 = new javax.swing.JTextField();
        jbRemoveBooks = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtSearchAuthor5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButtonOn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("CCS Library");

        jbLogout.setBackground(new java.awt.Color(51, 51, 255));
        jbLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLogout.setForeground(new java.awt.Color(255, 255, 255));
        jbLogout.setText("LOGOUT");
        jbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSearch2.setBackground(java.awt.Color.lightGray);

        jLabel8.setText("Add books");

        jtSearchTittle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchTittle2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Title :");

        jLabel10.setText("Author:");

        jtSearchAuthor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchAuthor2ActionPerformed(evt);
            }
        });

        jbAdd.setText("ADD");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jLabel11.setText("Category:");

        jtSearchAuthor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchAuthor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSearch2Layout = new javax.swing.GroupLayout(jpSearch2);
        jpSearch2.setLayout(jpSearch2Layout);
        jpSearch2Layout.setHorizontalGroup(
            jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearch2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(243, 243, 243))
            .addGroup(jpSearch2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAdd)
                    .addComponent(jtSearchAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpSearch2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jtSearchAuthor3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtSearchTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSearch2Layout.setVerticalGroup(
            jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearch2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSearchTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtSearchAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtSearchAuthor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdd)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel13.setText("Category :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"All", "Business & Accounting", "Engineering", "Programming"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jpSearch3.setBackground(java.awt.Color.lightGray);

        jLabel12.setText("Remove books");

        jtSearchTittle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchTittle3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Title :");

        jLabel15.setText("Author:");

        jtSearchAuthor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchAuthor4ActionPerformed(evt);
            }
        });

        jbRemoveBooks.setText("REMOVE");
        jbRemoveBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveBooksActionPerformed(evt);
            }
        });

        jLabel16.setText("Category:");

        jtSearchAuthor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSearchAuthor5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSearch3Layout = new javax.swing.GroupLayout(jpSearch3);
        jpSearch3.setLayout(jpSearch3Layout);
        jpSearch3Layout.setHorizontalGroup(
            jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearch3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(243, 243, 243))
            .addGroup(jpSearch3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRemoveBooks)
                    .addComponent(jtSearchAuthor4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpSearch3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jtSearchAuthor5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtSearchTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSearch3Layout.setVerticalGroup(
            jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearch3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSearchTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtSearchAuthor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSearch3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtSearchAuthor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoveBooks)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("BOOKS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("BORROWED BOOKS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "Name", "Borrow date", "Return date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jToggleButtonOn.setText("Show");
        jToggleButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpSearch3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonOn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jToggleButtonOn))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogoutActionPerformed
      this.setVisible(false);
        
    }//GEN-LAST:event_jbLogoutActionPerformed

    private void jtSearchTittle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchTittle2ActionPerformed
        
    }//GEN-LAST:event_jtSearchTittle2ActionPerformed

    private void jtSearchAuthor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchAuthor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSearchAuthor2ActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {
        String title = jtSearchTittle2.getText().trim();
        String author = jtSearchAuthor2.getText().trim();
        String category = jtSearchAuthor3.getText().trim();

        Book newBook = new Book(title, author, category, true);
        books.add(newBook);

        populateTable1();
        populateTable2();
        dashboard.refreshBooksTable(); 

        jtSearchTittle2.setText("");
        jtSearchAuthor2.setText("");
        jtSearchAuthor3.setText("");

        JOptionPane.showMessageDialog(this, "Book added successfully!");
    }
    

    private void jtSearchAuthor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchAuthor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSearchAuthor3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      
    }//GEN-LAST:event_jTable2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtSearchTittle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchTittle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSearchTittle3ActionPerformed

    private void jtSearchAuthor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchAuthor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSearchAuthor4ActionPerformed

    private void jbRemoveBooksActionPerformed(java.awt.event.ActionEvent evt) {
        String title = jtSearchTittle3.getText().trim();
        String author = jtSearchAuthor4.getText().trim();
        String category = jtSearchAuthor5.getText().trim();
        boolean found = false;

        for (int i = 0; i < books.size(); i++) {
            Book book = books.get(i);
            if (book.getTittle().equalsIgnoreCase(title) && book.getAuthor().equalsIgnoreCase(author) && book.getCategory().equalsIgnoreCase(category)) {
                books.remove(i);
                found = true;
                break;
            }
        }

        populateTable1();
        populateTable2();
        dashboard.refreshBooksTable();

        jtSearchTittle3.setText("");
        jtSearchAuthor4.setText("");
        jtSearchAuthor5.setText("");

        if (found) {
            JOptionPane.showMessageDialog(this, "Book removed successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Book not found!");
        }
    }

    private void jtSearchAuthor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSearchAuthor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSearchAuthor5ActionPerformed

    private void jToggleButtonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOnActionPerformed
        updateJTable1WithBorrowedBooks();
    }//GEN-LAST:event_jToggleButtonOnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButtonOn;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbLogout;
    private javax.swing.JButton jbRemoveBooks;
    private javax.swing.JPanel jpSearch2;
    private javax.swing.JPanel jpSearch3;
    private javax.swing.JTextField jtSearchAuthor2;
    private javax.swing.JTextField jtSearchAuthor3;
    private javax.swing.JTextField jtSearchAuthor4;
    private javax.swing.JTextField jtSearchAuthor5;
    private javax.swing.JTextField jtSearchTittle2;
    private javax.swing.JTextField jtSearchTittle3;
    // End of variables declaration//GEN-END:variables
}
